### ISSUE TITLE
Restore releng for org.eclipse.mylyn.context

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-mylyn/org.eclipse.mylyn.context#7]
We should reanimate the releng for org.eclipse.mylyn.context and integrate it with GitHub actions

**Comment by wimjongman** [comment]
Should I create a job @ https://ci.eclipse.org/mylyn?

**Comment by ruspl-afed** [comment]
It is already there, see https://ci.eclipse.org/mylyn/job/github-mylyn-context/

**Comment by ruspl-afed** [comment]
We have good progress here: 222 tests passed and only 18 failed

**Comment by ruspl-afed** [comment]
Only 1 failing test left

**Comment by ruspl-afed** [comment]
CI/CD is up and running.
Only one test was disabled with https://github.com/eclipse-mylyn/org.eclipse.mylyn.context/issues/9
